services:
  postgres:
    image: postgres:18-alpine
    container_name: booking_postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_booking_data:/var/lib/postgresql
    networks:
      - booking-network
  
  valkey:
    image: valkey/valkey:9-alpine
    container_name: booking_valkey
    ports:
      - "6379:6379"
    networks:
      - booking-network
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: booking_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    networks:
      - booking-network
  
  mongo:
    image: mongo:8.0
    container_name: booking_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_booking_data:/data/db
    networks:
      - booking-network

volumes:
  postgres_booking_data:
  mongo_booking_data:

networks:
  booking-network:
    driver: bridge