services:
  postgres:
    image: postgres:18-alpine
    container_name: booking_postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_booking_data:/var/lib/postgresql
    networks:
      - booking-network
  
  valkey:
    image: valkey/valkey:9-alpine
    container_name: booking_valkey
    ports:
      - "6379:6379"
    networks:
      - booking-network
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: booking_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    networks:
      - booking-network
  
  mongo:
    image: mongo:8.0
    container_name: booking_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_booking_data:/data/db
    networks:
      - booking-network
  
  backend-api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    container_name: booking_api
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=booking_db;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD
      - ConnectionStrings__Mongo=mongodb://mongo:27017
      - ConnectionStrings__Valkey=valkey:6379
      - RabbitMq__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Test
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
      - valkey
      - rabbitmq
    networks:
      - booking-network

  client:
    container_name: booking_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    networks:
      - booking-network

volumes:
  postgres_booking_data:
  mongo_booking_data:

networks:
  booking-network:
    driver: bridge